import { useQuery } from '@tanstack/react-query'
import type { Vehicle } from '@/types/vehicle'
import { normalizeAuctionTimes } from '@/lib/auction'
import { buildVehicleIndex, type VehicleIndex } from '@/lib/vehicle-index'
import { perfEnd, perfLog, perfStart } from '@/lib/perf'

export type NormalizedVehicle = Vehicle & { auction_end: string }

/**
 * When VITE_USE_LARGE_DATASET=true, we point the fetch at the synthetic 20k
 * dataset generated by `scripts/generate-vehicles.ts`. The seed file at
 * `/data/vehicles.json` is never modified.
 */
const USE_LARGE_DATASET =
  typeof import.meta !== 'undefined' &&
  import.meta.env?.VITE_USE_LARGE_DATASET === 'true'

const DATASET_URL = USE_LARGE_DATASET
  ? '/data/vehicles-large.json'
  : '/data/vehicles.json'

async function fetchVehicles(): Promise<{
  vehicles: NormalizedVehicle[]
  byId: Map<string, NormalizedVehicle>
  index: VehicleIndex
}> {
  perfStart('data-load')

  perfStart('data-load/fetch')
  const res = await fetch(DATASET_URL)
  if (!res.ok) throw new Error(`Failed to load vehicles: ${res.status}`)
  const raw = (await res.json()) as Vehicle[]
  perfEnd('data-load/fetch', `${raw.length} records`)

  perfStart('data-load/normalize')
  const normalized = normalizeAuctionTimes(raw) as NormalizedVehicle[]
  perfEnd('data-load/normalize')

  perfStart('data-load/index')
  const byId = new Map<string, NormalizedVehicle>()
  for (const v of normalized) byId.set(v.id, v)
  const index = buildVehicleIndex(normalized)
  perfEnd('data-load/index')

  perfEnd('data-load', `${normalized.length} records, dataset=${USE_LARGE_DATASET ? 'large' : 'seed'}`)
  perfLog('data-load/dataset', DATASET_URL)

  return { vehicles: normalized, byId, index }
}

export function useVehicles() {
  return useQuery({
    queryKey: ['vehicles', USE_LARGE_DATASET ? 'large' : 'seed'],
    queryFn: fetchVehicles,
    // These defaults also live on the QueryClient; duplicated here for clarity
    // at the call site — this dataset is static for the session.
    staleTime: Infinity,
    gcTime: Infinity,
  })
}

export function useVehicle(id: string) {
  const { data, ...rest } = useVehicles()
  return {
    ...rest,
    data: data ? data.byId.get(id) ?? null : undefined,
  }
}
